In [2]:
data = {"raw_data": [None, 23, 45, None, 67, "NA", 89]}

cleaned_data = [x for x in data["raw_data"] if x not in [None, "NA"]]

print("Raw Data:", data["raw_data"])
print("Cleaned Data:", cleaned_data)

Raw Data: [None, 23, 45, None, 67, 'NA', 89]
Cleaned Data: [23, 45, 67, 89]

In [3]:
import pandas as pd

In [4]:
data = {
    "Name": ["Alice", "Bob", None, "David"],
    "Age": [25, None, 30, "NA"]
}

df = pd.DataFrame(data)
df

    Name   Age
0  Alice    25
1    Bob  None
2   None    30
3  David    NA

In [5]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df

    Name   Age
0  Alice  25.0
1    Bob   NaN
2   None  30.0
3  David   NaN

In [6]:
df_cleaned = df.dropna()
df_cleaned

    Name   Age
0  Alice  25.0

In [7]:
print("Original Data")
print(df)

print("\nCleaned Data")
print(df_cleaned)

Original Data
    Name   Age
0  Alice  25.0
1    Bob   NaN
2   None  30.0
3  David   NaN

Cleaned Data
    Name   Age
0  Alice  25.0

In [8]:
import numpy as np

In [9]:
data = np.array([10, 20, 30, 40, 50])
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
normalized_data

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
print("Normalized Data:", normalized_data)

Normalized Data: [0.   0.25 0.5  0.75 1.  ]

In [11]:
data = {
    "Name": ["Alice", "Bob"],
    "Age": [25, 30]
}

df = pd.DataFrame(data)
df

    Name  Age
0  Alice   25
1    Bob   30

In [12]:
df.to_csv("example.csv", index=False)

In [13]:
df_read = pd.read_csv("example.csv")
df_read

    Name  Age
0  Alice   25
1    Bob   30

In [14]:
import json

In [15]:
data = '{"Name":"Alice","Age":25}'
parsed_data = json.loads(data)
parsed_data

{'Name': 'Alice', 'Age': 25}

In [16]:
import xml.etree.ElementTree as ET

In [17]:
xml_data = "<person><name>Alice</name><age>25</age></person>"

root = ET.fromstring(xml_data)

print("Name:", root.find("name").text)
print("Age:", root.find("age").text)

Name: Alice
Age: 25

In [18]:
import sqlite3

In [19]:
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

In [20]:
cursor.execute("CREATE TABLE users(id INTEGER,name TEXT,age INTEGER)")
cursor.execute("INSERT INTO users VALUES(1,'Alice',25)")
conn.commit()

In [21]:
cursor.execute("PRAGMA table_info(users)")
schema = cursor.fetchall()
schema

[(0, 'id', 'INTEGER', 0, None, 0),
 (1, 'name', 'TEXT', 0, None, 0),
 (2, 'age', 'INTEGER', 0, None, 0)]

In [22]:
print("Database Schema")

for column in schema:
    print(column)

Database Schema
(0, 'id', 'INTEGER', 0, None, 0)
(1, 'name', 'TEXT', 0, None, 0)
(2, 'age', 'INTEGER', 0, None, 0)